export const HELMET_BOOT_LINE = "ANDREW ALFRED TRIMBLE // HELMET LINK STABLE";
export const HELMET_BOOT_CHAR_MS = 42;
export const HELMET_BOOT_SCREEN_DELAY_S = 0.18;
export const HELMET_BOOT_SCREEN_STAGGER_S = 0.13;
